/**
 * XOS Salesforce configuration. Keep every Salesforce API field and
 * organization-specific picklist value here so the adapter remains portable.
 */
const mapping = {
  apiVersion: "v67.0",
  objects: {
    account: {
      name: "Account",
      fields: {
        id: "Id",
        name: "Name",
        industry: "Industry",
        employeeCount: "Nombre_employes__c",
        customerType: "Type_de_client__c",
        parentId: "ParentId",
        ownerId: "OwnerId",
      },
      employeeBands: [
        "1 - 50",
        "51 - 250",
        "251 - 500",
        "501 - 1000",
        "1001 - 2000",
        "2001 - 4999",
        "5000 et plus",
      ],
      customerTypes: ["Client inactif", "Client", "Prospect"],
      industries: [
        "Secteur public",
        "Aéronautique et Défense",
        "Biens de consommation alimentaires",
        "Communication et Médias",
        "Distribution spécialisée",
        "Divertissement",
        "E-Commerce, VAD",
        "Editeur de logiciels",
        "Education - Formation",
        "Entité à but non lucratif",
        "Environnement",
        "Finance",
        "Grande distribution alimentaire",
        "Industrie de l'emballage",
        "Matériaux de construction et extraction d'autres matériaux (hors énergie)",
        "Messagerie, courrier",
        "Ordinateurs & Electronique grand public",
        "Portails, pure players Internet",
        "Relation Client",
        "Services aux entreprises ou aux collectivités",
        "Services de conseils",
        "Services informatiques",
        "Télévision, radio, cinéma",
        "Transports",
        "Publicité/Marketing/Relations publiques",
        "BTP / construction",
        "Chimie (fine et lourde) / plastique",
        "Agroalimentaire / agriculture",
        "Assurance / Réassurance / caisses de retraite",
        "Automobiles / équipementiers",
        "Banque / finance",
        "Construction mécanique / métallurgie / sidérurgie / machines-outils",
        "Culture & Loisirs",
        "Distribution BtoB",
        "Droguerie / parfumerie / hygiène / cosmétiques",
        "Energie",
        "Equipement de la maison / électroménager",
        "Equipement de la personne (vêtements, accessoires)",
        "Etablissements médicaux / centre de soins",
        "Immobilier / promotion immobilière",
        "Ingénierie / certifications et inspections techniques",
        "Luxe",
        "Matériels et composants électroniques / électriques / informatique",
        "Presse / édition / imprimerie",
        "Restauration collective / chaînes",
        "Santé / pharmacie / biotech",
        "Services à la personne / action sociale",
        "Services environnementaux / facility management",
        "Support, maintenance et logistique",
        "Télécommunications",
        "Tourisme / hôtellerie",
      ],
    },
    contact: {
      name: "Contact",
      fields: {
        id: "Id",
        name: "Name",
        phone: "Phone",
        accountId: "AccountId",
        title: "Title",
        linkedin: "Profil_Linkedin__c",
        email: "Email",
        mobilePhone: "MobilePhone",
        decisionLevel: "Niveau_de_d_cision__c",
        doNotCall: "NPA__c",
      },
      decisionLevels: ["+", "=", "-"],
      fonctionPresets: [
        {
          id: "responsable_formation",
          label: "Responsable formation",
          likes: ["%responsable%formation%"],
          exacts: ["RF"],
        },
        {
          id: "directeur_formation",
          label: "Directeur formation",
          likes: ["%direct%formation%"],
          exacts: ["DF"],
        },
        {
          id: "digital_learning_manager",
          label: "Digital learning manager",
          likes: ["%digital learning%", "%e-learning%", "%elearning%"],
          exacts: [],
        },
        {
          id: "charge_formation",
          label: "Chargé de formation",
          likes: [
            "%charg%formation%",
            "%chef de projet formation%",
            "%training manager%",
            "%learning manager%",
            "%training officer%",
            "%training coordinator%",
            "%gestionnaire%formation%",
          ],
          exacts: ["CF", "CP"],
        },
      ],
    },
    task: {
      name: "Task",
      childRelationship: "Tasks",
      fields: {
        id: "Id",
        subject: "Subject",
        description: "Description",
        result: "Resultat_call__c",
        subtype: "TaskSubtype",
        duration: "CallDurationInSeconds",
        whoId: "WhoId",
        whatId: "WhatId",
        status: "Status",
        ownerId: "OwnerId",
        activityDate: "ActivityDate",
      },
      subtypeValue: "Call",
      statusValue: "Achevée",
      results: [
        "Appel non décroché",
        "Message répondeur",
        "Appel décroché",
        "Appel argumenté",
        "RDV planifié",
      ],
      resultSemantic: {
        rdv: "RDV planifié",
        followUpNoAnswer: "Appel non décroché",
        followUpVoicemail: "Message répondeur",
      },
    },
    opportunity: {
      name: "Opportunity",
      fields: {
        accountId: "AccountId",
        isClosed: "IsClosed",
        isWon: "IsWon",
        stageName: "StageName",
      },
      closedLostStage: "Fermée / Perdue",
    },
    event: {
      name: "Event",
      relationName: "EventRelation",
      fields: {
        subject: "Subject",
        startDateTime: "StartDateTime",
        endDateTime: "EndDateTime",
        whoId: "WhoId",
        whatId: "WhatId",
        ownerId: "OwnerId",
        relationId: "RelationId",
        eventId: "EventId",
      },
    },
  },
};

export default mapping;
